# Site settings
title: mantha.io
header-img: img/home-bg.jpg
email: sriram.mantha@gmail.com
description: "code, tech, gadgets and some ramblings"
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: sriramreloaded
github_username:  manthasriram	
facebook_username:  mantha_sriram

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
