# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: sriram.mantha@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: sriramreloaded
github_username:  manthasriram	
facebook_username:  mantha_sriram

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
