# Site settings
title: sriram.mantha.io
header-img: img/home-bg.jpg
email: sriram.mantha@gmail.com
description: "code, tech, gadgets and some ramblings"
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: sriramreloaded
github_username:  manthasriram	
facebook_username:  mantha_sriram

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
